version: '3.8'

services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_ENV: prod
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - internal

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - internal

  caddy:
    image: dunglas/frankenphp
    depends_on:
      - php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/app/public
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - internal

volumes:
  db_data:
  caddy_data:
  caddy_config:

networks:
  internal:
