services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    ports:
      - "80:80"
      - "8443:443"
    volumes:
      - database_data:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"
