controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

frontend:
    path: /{any}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: 'base.html.twig'
    requirements:
        any: ".+"
