parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Déclare explicitement le Subscriber
    App\EventSubscriber\AdvertissementSubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }

    # Déclare explicitement le DataPersister si nécessaire
    App\DataPersister\AdvertissementDataPersister:
        tags: ['api_platform.state_processor']
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
